services:
  db_products:
    image: postgres:latest
    container_name: db_products_container 
    environment:
      POSTGRES_USER: user_products       
      POSTGRES_PASSWORD: password_products 
      POSTGRES_DB: db_products 
    ports:
      - "5442:5432" 
    volumes:
      - ./db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data_products:/var/lib/postgresql/data

volumes:
  postgres_data_products:
