\c db_products

-- Tabla de Tipos de Productos
CREATE TABLE IF NOT EXISTS types (
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL UNIQUE,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Tabla de Productos
CREATE TABLE IF NOT EXISTS products ( 
	id SERIAL PRIMARY KEY, 
	name VARCHAR(255) NOT NULL, 
	description TEXT, 
	price NUMERIC(10, 2) NOT NULL, 
	typeid INTEGER REFERENCES types(id) ON DELETE RESTRICT,
	active BOOLEAN DEFAULT TRUE, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
